import { createContext, useContext, useState, useEffect } from 'react'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Comprehensive Translations
const resources = {
  en: {
    translation: {
      // Navigation
      dashboard: 'Dashboard',
      products: 'Products',
      orders: 'Orders',
      stakeholders: 'Stakeholders',
      inviteMembers: 'Invite Members',
      marketing: 'Marketing',
      forecasting: 'Forecasting',
      shipping: 'Shipping',
      settings: 'Settings',
      stock: 'Stock',
      chat: 'Chat',

      // Common
      welcome: 'Welcome back',
      welcomeBack: 'Welcome back',
      search: 'Search',
      searchPlaceholder: 'Search...',
      filter: 'Filter',
      filterBy: 'Filter by',
      save: 'Save',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      view: 'View',
      viewAll: 'View all',
      loading: 'Loading...',
      noData: 'No data available',
      close: 'Close',
      confirm: 'Confirm',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      all: 'All',
      active: 'Active',
      inactive: 'Inactive',
      status: 'Status',
      actions: 'Actions',
      details: 'Details',
      description: 'Description',
      date: 'Date',
      time: 'Time',
      name: 'Name',
      type: 'Type',
      amount: 'Amount',
      total: 'Total',
      price: 'Price',
      quantity: 'Quantity',
      unit: 'Unit',
      notes: 'Notes',
      created: 'Created',
      updated: 'Updated',
      by: 'by',

      // Auth
      signIn: 'Sign In',
      signOut: 'Sign Out',
      logout: 'Logout',
      register: 'Register',
      email: 'Email',
      password: 'Password',
      inviteCode: 'Invite Code',
      forgotPassword: 'Forgot Password?',
      rememberMe: 'Remember me',

      // Dashboard
      heresWhatsHappening: "Here's what's happening with your portfolio",
      yourShares: 'Your Shares',
      yourTier: 'Your Tier',
      totalPool: 'Total Pool',
      orderContribution: 'Order Contribution',
      ownership: 'ownership',
      invested: 'invested',
      activeStakeholders: 'active stakeholders',
      participationShares: 'participation shares',
      poolRevenue: 'Pool Revenue',
      lastMonths: 'Last {count} months',
      lastYear: 'Last year',
      shareDistributionByTier: 'Share Distribution by Tier',
      activeGroupOrders: 'Active Group Orders',
      noActiveGroupOrders: 'No active group orders',
      createOne: 'Create one',
      participants: 'participants',
      complete: 'complete',
      topStakeholders: 'Top Stakeholders',
      shares: 'shares',
      joinGroupOrder: 'Join Group Order',
      groupOrder: 'Group Order',

      // Products
      productName: 'Product Name',
      category: 'Category',
      categories: 'Categories',
      basePrice: 'Base Price',
      stockLevel: 'Stock Level',
      bulkPricing: 'Bulk Pricing',
      inStock: 'In Stock',
      lowStock: 'Low Stock',
      outOfStock: 'Out of Stock',
      addProduct: 'Add Product',
      editProduct: 'Edit Product',
      deleteProduct: 'Delete Product',
      productDetails: 'Product Details',
      minQuantity: 'Min Quantity',
      discount: 'Discount',
      supplier: 'Supplier',
      sku: 'SKU',
      unitPrice: 'Unit Price',

      // Stock
      stockManagement: 'Stock Management',
      manageInventory: 'Manage your product inventory and stock levels',
      currentStock: 'Current Stock',
      reserved: 'Reserved',
      available: 'Available',
      reorderPoint: 'Reorder Point',
      leadTime: 'Lead Time',
      days: 'days',
      location: 'Location',
      warehouse: 'Warehouse',
      lastUpdated: 'Last Updated',
      stockConfiguration: 'Stock Configuration',
      updateStock: 'Update Stock',
      stockHistory: 'Stock History',
      lowStockAlert: 'Low Stock Alert',
      outOfStockAlert: 'Out of Stock Alert',
      reorderRequired: 'Reorder Required',
      stockStatus: 'Stock Status',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      critical: 'Critical',
      units: 'units',

      // Orders
      groupOrders: 'Group Orders',
      myOrders: 'My Orders',
      joinOrder: 'Join Order',
      createOrder: 'Create Order',
      orderStatus: 'Order Status',
      pending: 'Pending',
      confirmed: 'Confirmed',
      processing: 'Processing',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
      orderDate: 'Order Date',
      deliveryDate: 'Delivery Date',
      trackingNumber: 'Tracking Number',
      orderTotal: 'Order Total',
      orderDetails: 'Order Details',
      orderHistory: 'Order History',
      targetQuantity: 'Target Quantity',
      currentQuantity: 'Current Quantity',
      progressToTarget: 'Progress to Target',
      joinThisOrder: 'Join This Order',
      leaveOrder: 'Leave Order',
      closeOrder: 'Close Order',

      // Stakeholders
      totalShares: 'Total Shares',
      investment: 'Investment',
      tier: 'Tier',
      addInvestment: 'Add Investment',
      invite: 'Invite',
      inviteStakeholder: 'Invite Stakeholder',
      stakeholderDetails: 'Stakeholder Details',
      memberSince: 'Member Since',
      lastActivity: 'Last Activity',
      totalInvestment: 'Total Investment',
      sharePercentage: 'Share Percentage',
      platinum: 'Platinum',
      gold: 'Gold',
      silver: 'Silver',
      bronze: 'Bronze',
      investmentHistory: 'Investment History',
      dividendHistory: 'Dividend History',

      // Marketing
      campaigns: 'Campaigns',
      activeCampaigns: 'Active Campaigns',
      createCampaign: 'Create Campaign',
      campaignName: 'Campaign Name',
      campaignType: 'Campaign Type',
      startDate: 'Start Date',
      endDate: 'End Date',
      budget: 'Budget',
      spent: 'Spent',
      remaining: 'Remaining',
      impressions: 'Impressions',
      clicks: 'Clicks',
      conversions: 'Conversions',
      roi: 'ROI',
      performance: 'Performance',
      analytics: 'Analytics',
      reach: 'Reach',
      engagement: 'Engagement',

      // Forecasting
      priceForecast: 'Price Forecast',
      marketTrends: 'Market Trends',
      demandPrediction: 'Demand Prediction',
      forecastPeriod: 'Forecast Period',
      confidence: 'Confidence',
      predicted: 'Predicted',
      actual: 'Actual',
      variance: 'Variance',
      trend: 'Trend',
      upward: 'Upward',
      downward: 'Downward',
      stable: 'Stable',
      volatile: 'Volatile',

      // Shipping
      shipments: 'Shipments',
      trackShipment: 'Track Shipment',
      shippingAddress: 'Shipping Address',
      billingAddress: 'Billing Address',
      carrier: 'Carrier',
      estimatedDelivery: 'Estimated Delivery',
      actualDelivery: 'Actual Delivery',
      shippingCost: 'Shipping Cost',
      shippingMethod: 'Shipping Method',
      standard: 'Standard',
      express: 'Express',
      overnight: 'Overnight',
      aggregatedShipping: 'Aggregated Shipping',
      individualShipping: 'Individual Shipping',
      inTransit: 'In Transit',
      outForDelivery: 'Out for Delivery',
      deliveryException: 'Delivery Exception',

      // Settings
      profile: 'Profile',
      profileInformation: 'Profile Information',
      notifications: 'Notifications',
      notificationPreferences: 'Notification Preferences',
      language: 'Language',
      theme: 'Theme',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      dark: 'Dark',
      light: 'Light',
      display: 'Display',
      displaySettings: 'Display Settings',
      currency: 'Currency',
      timezone: 'Timezone',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      orderUpdates: 'Order Updates',
      priceAlerts: 'Price Alerts',
      marketingEmails: 'Marketing emails',
      receiveNotifications: 'Receive notifications via email',
      browserNotifications: 'Browser push notifications',
      updatesOnOrders: 'Updates on your orders and shipments',
      alertsWhenPrices: 'Alerts when prices change significantly',
      newsPromotions: 'News, promotions, and updates',
      security: 'Security',
      securitySettings: 'Security Settings',
      changePassword: 'Change Password',
      updatePassword: 'Update your account password',
      twoFactorAuth: 'Two-Factor Authentication',
      addExtraSecurity: 'Add an extra layer of security',
      activeSessions: 'Active Sessions',
      manageDevices: 'Manage your logged-in devices',
      deleteAccount: 'Delete Account',
      permanentlyDelete: 'Permanently delete your account and data',
      integrations: 'Integrations',
      connectedServices: 'Connected Services',
      connected: 'Connected',
      connect: 'Connect',
      disconnect: 'Disconnect',
      fullName: 'Full Name',
      streetAddress: 'Street Address',
      city: 'City',
      postalCode: 'Postal Code',
      country: 'Country',
      defaultShippingAddress: 'Default Shipping Address',
      preferAggregatedShipping: 'Prefer Aggregated Shipping',
      combineOrders: 'Combine orders with other stakeholders for lower shipping costs',
      settingsSaved: 'Settings saved successfully',
      failedToSave: 'Failed to save settings',
      saving: 'Saving...',
      brightTheme: 'Bright theme',
      easyOnEyes: 'Easy on eyes',
      enable: 'Enable',
      change: 'Change',

      // Chat
      typeMessage: 'Type a message...',
      send: 'Send',
      onlineUsers: 'Online Users',
      online: 'online',
      allMessages: 'All Messages',
      noMessages: 'No messages yet',
      startConversation: 'Start the conversation!',

      // Investment Allocation
      investmentAllocation: 'Investment Allocation',
      myAllocation: 'My Allocation',
      stakeholderParticipation: 'Stakeholder Participation',
      allocatedAmount: 'Allocated Amount',
      optedOut: 'Opted Out',
      setAllocation: 'Set Allocation',
      allocationSaved: 'Allocation saved',
      saved: 'Saved',
      allocated: 'allocated',
      ofStakeholders: 'of stakeholders',
      participationRate: 'Participation Rate',
      optedOutDescription: 'You have opted out of investment for this product. You can still participate in orders.',

      // Product Discussion
      productDiscussion: 'Product Discussion',
      discuss: 'Discuss',
      recentMessages: 'recent messages',
      joinDiscussion: 'Join Discussion',
      noDiscussionsYet: 'No discussions yet',
      startDiscussion: 'Start the discussion!',

      // Validation & Errors
      required: 'Required',
      invalid: 'Invalid',
      invalidEmail: 'Invalid email address',
      passwordTooShort: 'Password is too short',
      passwordsDoNotMatch: 'Passwords do not match',
      somethingWentWrong: 'Something went wrong',
      tryAgain: 'Try again',
      noResults: 'No results found',

      // Time
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'This Week',
      thisMonth: 'This Month',
      lastWeek: 'Last Week',
      lastMonth: 'Last Month',

      // Misc
      copyright: 'All rights reserved',
      version: 'Version',
      help: 'Help',
      support: 'Support',
      documentation: 'Documentation',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service'
    }
  },
  nl: {
    translation: {
      // Navigation
      dashboard: 'Dashboard',
      products: 'Producten',
      orders: 'Bestellingen',
      stakeholders: 'Aandeelhouders',
      marketing: 'Marketing',
      forecasting: 'Voorspelling',
      shipping: 'Verzending',
      settings: 'Instellingen',
      stock: 'Voorraad',
      chat: 'Chat',

      // Common
      welcome: 'Welkom',
      welcomeBack: 'Welkom terug',
      search: 'Zoeken',
      searchPlaceholder: 'Zoeken...',
      filter: 'Filteren',
      filterBy: 'Filteren op',
      save: 'Opslaan',
      saveChanges: 'Wijzigingen opslaan',
      cancel: 'Annuleren',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      add: 'Toevoegen',
      view: 'Bekijken',
      viewAll: 'Alles bekijken',
      loading: 'Laden...',
      noData: 'Geen gegevens beschikbaar',
      close: 'Sluiten',
      confirm: 'Bevestigen',
      back: 'Terug',
      next: 'Volgende',
      previous: 'Vorige',
      all: 'Alle',
      active: 'Actief',
      inactive: 'Inactief',
      status: 'Status',
      actions: 'Acties',
      details: 'Details',
      description: 'Beschrijving',
      date: 'Datum',
      time: 'Tijd',
      name: 'Naam',
      type: 'Type',
      amount: 'Bedrag',
      total: 'Totaal',
      price: 'Prijs',
      quantity: 'Hoeveelheid',
      unit: 'Eenheid',
      notes: 'Notities',
      created: 'Aangemaakt',
      updated: 'Bijgewerkt',
      by: 'door',

      // Auth
      signIn: 'Inloggen',
      signOut: 'Uitloggen',
      logout: 'Uitloggen',
      register: 'Registreren',
      email: 'E-mail',
      password: 'Wachtwoord',
      inviteCode: 'Uitnodigingscode',
      forgotPassword: 'Wachtwoord vergeten?',
      rememberMe: 'Onthoud mij',

      // Dashboard
      heresWhatsHappening: "Dit is wat er gebeurt met je portfolio",
      yourShares: 'Jouw Aandelen',
      yourTier: 'Jouw Niveau',
      totalPool: 'Totale Pool',
      orderContribution: 'Bestelbijdrage',
      ownership: 'eigendom',
      invested: 'geïnvesteerd',
      activeStakeholders: 'actieve aandeelhouders',
      participationShares: 'participatie-aandelen',
      poolRevenue: 'Pool Inkomsten',
      lastMonths: 'Laatste {count} maanden',
      lastYear: 'Afgelopen jaar',
      shareDistributionByTier: 'Aandelenverdeling per Niveau',
      activeGroupOrders: 'Actieve Groepsbestellingen',
      noActiveGroupOrders: 'Geen actieve groepsbestellingen',
      createOne: 'Maak er een',
      participants: 'deelnemers',
      complete: 'voltooid',
      topStakeholders: 'Top Aandeelhouders',
      shares: 'aandelen',
      joinGroupOrder: 'Groepsbestelling Deelnemen',
      groupOrder: 'Groepsbestelling',

      // Products
      productName: 'Productnaam',
      category: 'Categorie',
      categories: 'Categorieën',
      basePrice: 'Basisprijs',
      stockLevel: 'Voorraadniveau',
      bulkPricing: 'Staffelkorting',
      inStock: 'Op voorraad',
      lowStock: 'Lage voorraad',
      outOfStock: 'Niet op voorraad',
      addProduct: 'Product toevoegen',
      editProduct: 'Product bewerken',
      deleteProduct: 'Product verwijderen',
      productDetails: 'Productdetails',
      minQuantity: 'Min. hoeveelheid',
      discount: 'Korting',
      supplier: 'Leverancier',
      sku: 'SKU',
      unitPrice: 'Eenheidsprijs',

      // Stock
      stockManagement: 'Voorraadbeheer',
      manageInventory: 'Beheer je productvoorraad en voorraadniveaus',
      currentStock: 'Huidige Voorraad',
      reserved: 'Gereserveerd',
      available: 'Beschikbaar',
      reorderPoint: 'Bestelpunt',
      leadTime: 'Levertijd',
      days: 'dagen',
      location: 'Locatie',
      warehouse: 'Magazijn',
      lastUpdated: 'Laatst bijgewerkt',
      stockConfiguration: 'Voorraadconfiguratie',
      updateStock: 'Voorraad bijwerken',
      stockHistory: 'Voorraadgeschiedenis',
      lowStockAlert: 'Lage voorraad waarschuwing',
      outOfStockAlert: 'Niet op voorraad waarschuwing',
      reorderRequired: 'Nabestelling vereist',
      stockStatus: 'Voorraadstatus',
      high: 'Hoog',
      medium: 'Gemiddeld',
      low: 'Laag',
      critical: 'Kritiek',
      units: 'eenheden',

      // Orders
      groupOrders: 'Groepsbestellingen',
      myOrders: 'Mijn Bestellingen',
      joinOrder: 'Deelnemen',
      createOrder: 'Bestelling Maken',
      orderStatus: 'Bestelstatus',
      pending: 'In behandeling',
      confirmed: 'Bevestigd',
      processing: 'Verwerken',
      shipped: 'Verzonden',
      delivered: 'Geleverd',
      cancelled: 'Geannuleerd',
      orderDate: 'Besteldatum',
      deliveryDate: 'Leverdatum',
      trackingNumber: 'Trackingnummer',
      orderTotal: 'Besteltotaal',
      orderDetails: 'Besteldetails',
      orderHistory: 'Bestelgeschiedenis',
      targetQuantity: 'Doelhoeveelheid',
      currentQuantity: 'Huidige hoeveelheid',
      progressToTarget: 'Voortgang naar doel',
      joinThisOrder: 'Deelnemen aan deze bestelling',
      leaveOrder: 'Bestelling verlaten',
      closeOrder: 'Bestelling sluiten',

      // Stakeholders
      totalShares: 'Totaal Aandelen',
      investment: 'Investering',
      tier: 'Niveau',
      addInvestment: 'Investering Toevoegen',
      invite: 'Uitnodigen',
      inviteStakeholder: 'Aandeelhouder Uitnodigen',
      stakeholderDetails: 'Aandeelhoudersdetails',
      memberSince: 'Lid sinds',
      lastActivity: 'Laatste activiteit',
      totalInvestment: 'Totale Investering',
      sharePercentage: 'Aandeelpercentage',
      platinum: 'Platina',
      gold: 'Goud',
      silver: 'Zilver',
      bronze: 'Brons',
      investmentHistory: 'Investeringsgeschiedenis',
      dividendHistory: 'Dividendgeschiedenis',

      // Marketing
      campaigns: 'Campagnes',
      activeCampaigns: 'Actieve Campagnes',
      createCampaign: 'Campagne Maken',
      campaignName: 'Campagnenaam',
      campaignType: 'Campagnetype',
      startDate: 'Startdatum',
      endDate: 'Einddatum',
      budget: 'Budget',
      spent: 'Uitgegeven',
      remaining: 'Resterend',
      impressions: 'Vertoningen',
      clicks: 'Klikken',
      conversions: 'Conversies',
      roi: 'ROI',
      performance: 'Prestaties',
      analytics: 'Analytics',
      reach: 'Bereik',
      engagement: 'Betrokkenheid',

      // Forecasting
      priceForecast: 'Prijsvoorspelling',
      marketTrends: 'Markttrends',
      demandPrediction: 'Vraagvoorspelling',
      forecastPeriod: 'Voorspellingsperiode',
      confidence: 'Betrouwbaarheid',
      predicted: 'Voorspeld',
      actual: 'Werkelijk',
      variance: 'Afwijking',
      trend: 'Trend',
      upward: 'Stijgend',
      downward: 'Dalend',
      stable: 'Stabiel',
      volatile: 'Volatiel',

      // Shipping
      shipments: 'Zendingen',
      trackShipment: 'Zending Volgen',
      shippingAddress: 'Verzendadres',
      billingAddress: 'Factuuradres',
      carrier: 'Vervoerder',
      estimatedDelivery: 'Geschatte Levering',
      actualDelivery: 'Werkelijke Levering',
      shippingCost: 'Verzendkosten',
      shippingMethod: 'Verzendmethode',
      standard: 'Standaard',
      express: 'Express',
      overnight: 'Overnight',
      aggregatedShipping: 'Geaggregeerde Verzending',
      individualShipping: 'Individuele Verzending',
      inTransit: 'Onderweg',
      outForDelivery: 'Wordt bezorgd',
      deliveryException: 'Leveringsuitzondering',

      // Settings
      profile: 'Profiel',
      profileInformation: 'Profielinformatie',
      notifications: 'Meldingen',
      notificationPreferences: 'Meldingsvoorkeuren',
      language: 'Taal',
      theme: 'Thema',
      darkMode: 'Donkere Modus',
      lightMode: 'Lichte Modus',
      dark: 'Donker',
      light: 'Licht',
      display: 'Weergave',
      displaySettings: 'Weergave-instellingen',
      currency: 'Valuta',
      timezone: 'Tijdzone',
      emailNotifications: 'E-mailmeldingen',
      pushNotifications: 'Push-meldingen',
      orderUpdates: 'Bestelupdates',
      priceAlerts: 'Prijswaarschuwingen',
      marketingEmails: 'Marketing e-mails',
      receiveNotifications: 'Ontvang meldingen via e-mail',
      browserNotifications: 'Browser push-meldingen',
      updatesOnOrders: 'Updates over je bestellingen en zendingen',
      alertsWhenPrices: 'Waarschuwingen bij significante prijswijzigingen',
      newsPromotions: 'Nieuws, promoties en updates',
      security: 'Beveiliging',
      securitySettings: 'Beveiligingsinstellingen',
      changePassword: 'Wachtwoord Wijzigen',
      updatePassword: 'Werk je accountwachtwoord bij',
      twoFactorAuth: 'Twee-Factor Authenticatie',
      addExtraSecurity: 'Voeg een extra beveiligingslaag toe',
      activeSessions: 'Actieve Sessies',
      manageDevices: 'Beheer je ingelogde apparaten',
      deleteAccount: 'Account Verwijderen',
      permanentlyDelete: 'Verwijder je account en gegevens permanent',
      integrations: 'Integraties',
      connectedServices: 'Verbonden Diensten',
      connected: 'Verbonden',
      connect: 'Verbinden',
      disconnect: 'Ontkoppelen',
      fullName: 'Volledige Naam',
      streetAddress: 'Straatnaam',
      city: 'Stad',
      postalCode: 'Postcode',
      country: 'Land',
      defaultShippingAddress: 'Standaard Verzendadres',
      preferAggregatedShipping: 'Geaggregeerde Verzending Prefereren',
      combineOrders: 'Combineer bestellingen met andere aandeelhouders voor lagere verzendkosten',
      settingsSaved: 'Instellingen succesvol opgeslagen',
      failedToSave: 'Opslaan mislukt',
      saving: 'Opslaan...',
      brightTheme: 'Licht thema',
      easyOnEyes: 'Prettig voor de ogen',
      enable: 'Inschakelen',
      change: 'Wijzigen',

      // Chat
      typeMessage: 'Typ een bericht...',
      send: 'Versturen',
      onlineUsers: 'Online Gebruikers',
      online: 'online',
      allMessages: 'Alle Berichten',
      noMessages: 'Nog geen berichten',
      startConversation: 'Start het gesprek!',

      // Investment Allocation
      investmentAllocation: 'Investeringsallocatie',
      myAllocation: 'Mijn Allocatie',
      stakeholderParticipation: 'Aandeelhoudersparticipatie',
      allocatedAmount: 'Toegewezen Bedrag',
      optedOut: 'Afgemeld',
      setAllocation: 'Allocatie Instellen',
      allocationSaved: 'Allocatie opgeslagen',
      saved: 'Opgeslagen',
      allocated: 'toegewezen',
      ofStakeholders: 'van aandeelhouders',
      participationRate: 'Participatiegraad',
      optedOutDescription: 'Je hebt je afgemeld voor investering in dit product. Je kunt nog steeds deelnemen aan bestellingen.',

      // Product Discussion
      productDiscussion: 'Productdiscussie',
      discuss: 'Bespreken',
      recentMessages: 'recente berichten',
      joinDiscussion: 'Discussie Deelnemen',
      noDiscussionsYet: 'Nog geen discussies',
      startDiscussion: 'Start de discussie!',

      // Validation & Errors
      required: 'Verplicht',
      invalid: 'Ongeldig',
      invalidEmail: 'Ongeldig e-mailadres',
      passwordTooShort: 'Wachtwoord is te kort',
      passwordsDoNotMatch: 'Wachtwoorden komen niet overeen',
      somethingWentWrong: 'Er is iets misgegaan',
      tryAgain: 'Probeer opnieuw',
      noResults: 'Geen resultaten gevonden',

      // Time
      today: 'Vandaag',
      yesterday: 'Gisteren',
      thisWeek: 'Deze Week',
      thisMonth: 'Deze Maand',
      lastWeek: 'Vorige Week',
      lastMonth: 'Vorige Maand',

      // Misc
      copyright: 'Alle rechten voorbehouden',
      version: 'Versie',
      help: 'Help',
      support: 'Ondersteuning',
      documentation: 'Documentatie',
      privacyPolicy: 'Privacybeleid',
      termsOfService: 'Algemene Voorwaarden'
    }
  },
  de: {
    translation: {
      // Navigation
      dashboard: 'Dashboard',
      products: 'Produkte',
      orders: 'Bestellungen',
      stakeholders: 'Aktionäre',
      marketing: 'Marketing',
      forecasting: 'Prognose',
      shipping: 'Versand',
      settings: 'Einstellungen',
      stock: 'Lager',
      chat: 'Chat',

      // Common
      welcome: 'Willkommen',
      welcomeBack: 'Willkommen zurück',
      search: 'Suchen',
      searchPlaceholder: 'Suchen...',
      filter: 'Filtern',
      filterBy: 'Filtern nach',
      save: 'Speichern',
      saveChanges: 'Änderungen speichern',
      cancel: 'Abbrechen',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      add: 'Hinzufügen',
      view: 'Ansehen',
      viewAll: 'Alle ansehen',
      loading: 'Laden...',
      noData: 'Keine Daten verfügbar',
      close: 'Schließen',
      confirm: 'Bestätigen',
      back: 'Zurück',
      next: 'Weiter',
      previous: 'Zurück',
      all: 'Alle',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      status: 'Status',
      actions: 'Aktionen',
      details: 'Details',
      description: 'Beschreibung',
      date: 'Datum',
      time: 'Zeit',
      name: 'Name',
      type: 'Typ',
      amount: 'Betrag',
      total: 'Gesamt',
      price: 'Preis',
      quantity: 'Menge',
      unit: 'Einheit',
      notes: 'Notizen',
      created: 'Erstellt',
      updated: 'Aktualisiert',
      by: 'von',

      // Auth
      signIn: 'Anmelden',
      signOut: 'Abmelden',
      logout: 'Abmelden',
      register: 'Registrieren',
      email: 'E-Mail',
      password: 'Passwort',
      inviteCode: 'Einladungscode',
      forgotPassword: 'Passwort vergessen?',
      rememberMe: 'Angemeldet bleiben',

      // Dashboard
      heresWhatsHappening: "Das passiert mit Ihrem Portfolio",
      yourShares: 'Ihre Anteile',
      yourTier: 'Ihre Stufe',
      totalPool: 'Gesamtpool',
      orderContribution: 'Bestellbeitrag',
      ownership: 'Eigentum',
      invested: 'investiert',
      activeStakeholders: 'aktive Aktionäre',
      participationShares: 'Beteiligungsanteile',
      poolRevenue: 'Pool-Einnahmen',
      lastMonths: 'Letzte {count} Monate',
      lastYear: 'Letztes Jahr',
      shareDistributionByTier: 'Anteilsverteilung nach Stufe',
      activeGroupOrders: 'Aktive Gruppenbestellungen',
      noActiveGroupOrders: 'Keine aktiven Gruppenbestellungen',
      createOne: 'Erstellen Sie eine',
      participants: 'Teilnehmer',
      complete: 'abgeschlossen',
      topStakeholders: 'Top Aktionäre',
      shares: 'Anteile',
      joinGroupOrder: 'Gruppenbestellung beitreten',
      groupOrder: 'Gruppenbestellung',

      // Products
      productName: 'Produktname',
      category: 'Kategorie',
      categories: 'Kategorien',
      basePrice: 'Grundpreis',
      stockLevel: 'Lagerbestand',
      bulkPricing: 'Mengenrabatt',
      inStock: 'Auf Lager',
      lowStock: 'Niedriger Bestand',
      outOfStock: 'Nicht auf Lager',
      addProduct: 'Produkt hinzufügen',
      editProduct: 'Produkt bearbeiten',
      deleteProduct: 'Produkt löschen',
      productDetails: 'Produktdetails',
      minQuantity: 'Mindestmenge',
      discount: 'Rabatt',
      supplier: 'Lieferant',
      sku: 'SKU',
      unitPrice: 'Stückpreis',

      // Stock
      stockManagement: 'Lagerverwaltung',
      manageInventory: 'Verwalten Sie Ihren Produktbestand und Lagerbestände',
      currentStock: 'Aktueller Bestand',
      reserved: 'Reserviert',
      available: 'Verfügbar',
      reorderPoint: 'Nachbestellpunkt',
      leadTime: 'Lieferzeit',
      days: 'Tage',
      location: 'Standort',
      warehouse: 'Lager',
      lastUpdated: 'Zuletzt aktualisiert',
      stockConfiguration: 'Lagerkonfiguration',
      updateStock: 'Bestand aktualisieren',
      stockHistory: 'Bestandshistorie',
      lowStockAlert: 'Niedriger Bestand Warnung',
      outOfStockAlert: 'Nicht auf Lager Warnung',
      reorderRequired: 'Nachbestellung erforderlich',
      stockStatus: 'Lagerstatus',
      high: 'Hoch',
      medium: 'Mittel',
      low: 'Niedrig',
      critical: 'Kritisch',
      units: 'Einheiten',

      // Orders
      groupOrders: 'Gruppenbestellungen',
      myOrders: 'Meine Bestellungen',
      joinOrder: 'Beitreten',
      createOrder: 'Bestellung erstellen',
      orderStatus: 'Bestellstatus',
      pending: 'Ausstehend',
      confirmed: 'Bestätigt',
      processing: 'In Bearbeitung',
      shipped: 'Versendet',
      delivered: 'Geliefert',
      cancelled: 'Storniert',
      orderDate: 'Bestelldatum',
      deliveryDate: 'Lieferdatum',
      trackingNumber: 'Sendungsnummer',
      orderTotal: 'Bestellsumme',
      orderDetails: 'Bestelldetails',
      orderHistory: 'Bestellhistorie',
      targetQuantity: 'Zielmenge',
      currentQuantity: 'Aktuelle Menge',
      progressToTarget: 'Fortschritt zum Ziel',
      joinThisOrder: 'Dieser Bestellung beitreten',
      leaveOrder: 'Bestellung verlassen',
      closeOrder: 'Bestellung schließen',

      // Stakeholders
      totalShares: 'Gesamtanteile',
      investment: 'Investition',
      tier: 'Stufe',
      addInvestment: 'Investition hinzufügen',
      invite: 'Einladen',
      inviteStakeholder: 'Aktionär einladen',
      stakeholderDetails: 'Aktionärsdetails',
      memberSince: 'Mitglied seit',
      lastActivity: 'Letzte Aktivität',
      totalInvestment: 'Gesamtinvestition',
      sharePercentage: 'Anteilsprozentsatz',
      platinum: 'Platin',
      gold: 'Gold',
      silver: 'Silber',
      bronze: 'Bronze',
      investmentHistory: 'Investitionshistorie',
      dividendHistory: 'Dividendenhistorie',

      // Marketing
      campaigns: 'Kampagnen',
      activeCampaigns: 'Aktive Kampagnen',
      createCampaign: 'Kampagne erstellen',
      campaignName: 'Kampagnenname',
      campaignType: 'Kampagnentyp',
      startDate: 'Startdatum',
      endDate: 'Enddatum',
      budget: 'Budget',
      spent: 'Ausgegeben',
      remaining: 'Verbleibend',
      impressions: 'Impressionen',
      clicks: 'Klicks',
      conversions: 'Konversionen',
      roi: 'ROI',
      performance: 'Leistung',
      analytics: 'Analytik',
      reach: 'Reichweite',
      engagement: 'Engagement',

      // Forecasting
      priceForecast: 'Preisprognose',
      marketTrends: 'Markttrends',
      demandPrediction: 'Nachfrageprognose',
      forecastPeriod: 'Prognosezeitraum',
      confidence: 'Konfidenz',
      predicted: 'Vorhergesagt',
      actual: 'Tatsächlich',
      variance: 'Abweichung',
      trend: 'Trend',
      upward: 'Aufwärts',
      downward: 'Abwärts',
      stable: 'Stabil',
      volatile: 'Volatil',

      // Shipping
      shipments: 'Sendungen',
      trackShipment: 'Sendung verfolgen',
      shippingAddress: 'Lieferadresse',
      billingAddress: 'Rechnungsadresse',
      carrier: 'Spediteur',
      estimatedDelivery: 'Geschätzte Lieferung',
      actualDelivery: 'Tatsächliche Lieferung',
      shippingCost: 'Versandkosten',
      shippingMethod: 'Versandart',
      standard: 'Standard',
      express: 'Express',
      overnight: 'Über Nacht',
      aggregatedShipping: 'Sammelversand',
      individualShipping: 'Einzelversand',
      inTransit: 'Unterwegs',
      outForDelivery: 'In Zustellung',
      deliveryException: 'Lieferausnahme',

      // Settings
      profile: 'Profil',
      profileInformation: 'Profilinformationen',
      notifications: 'Benachrichtigungen',
      notificationPreferences: 'Benachrichtigungseinstellungen',
      language: 'Sprache',
      theme: 'Design',
      darkMode: 'Dunkler Modus',
      lightMode: 'Heller Modus',
      dark: 'Dunkel',
      light: 'Hell',
      display: 'Anzeige',
      displaySettings: 'Anzeigeeinstellungen',
      currency: 'Währung',
      timezone: 'Zeitzone',
      emailNotifications: 'E-Mail-Benachrichtigungen',
      pushNotifications: 'Push-Benachrichtigungen',
      orderUpdates: 'Bestellaktualisierungen',
      priceAlerts: 'Preiswarnungen',
      marketingEmails: 'Marketing-E-Mails',
      receiveNotifications: 'Benachrichtigungen per E-Mail erhalten',
      browserNotifications: 'Browser-Push-Benachrichtigungen',
      updatesOnOrders: 'Updates zu Ihren Bestellungen und Sendungen',
      alertsWhenPrices: 'Warnungen bei erheblichen Preisänderungen',
      newsPromotions: 'Neuigkeiten, Werbeaktionen und Updates',
      security: 'Sicherheit',
      securitySettings: 'Sicherheitseinstellungen',
      changePassword: 'Passwort ändern',
      updatePassword: 'Aktualisieren Sie Ihr Kontopasswort',
      twoFactorAuth: 'Zwei-Faktor-Authentifizierung',
      addExtraSecurity: 'Fügen Sie eine zusätzliche Sicherheitsebene hinzu',
      activeSessions: 'Aktive Sitzungen',
      manageDevices: 'Verwalten Sie Ihre angemeldeten Geräte',
      deleteAccount: 'Konto löschen',
      permanentlyDelete: 'Löschen Sie Ihr Konto und Ihre Daten dauerhaft',
      integrations: 'Integrationen',
      connectedServices: 'Verbundene Dienste',
      connected: 'Verbunden',
      connect: 'Verbinden',
      disconnect: 'Trennen',
      fullName: 'Vollständiger Name',
      streetAddress: 'Straße',
      city: 'Stadt',
      postalCode: 'Postleitzahl',
      country: 'Land',
      defaultShippingAddress: 'Standard-Lieferadresse',
      preferAggregatedShipping: 'Sammelversand bevorzugen',
      combineOrders: 'Bestellungen mit anderen Aktionären für niedrigere Versandkosten kombinieren',
      settingsSaved: 'Einstellungen erfolgreich gespeichert',
      failedToSave: 'Speichern fehlgeschlagen',
      saving: 'Speichern...',
      brightTheme: 'Helles Theme',
      easyOnEyes: 'Augenschonend',
      enable: 'Aktivieren',
      change: 'Ändern',

      // Chat
      typeMessage: 'Nachricht eingeben...',
      send: 'Senden',
      onlineUsers: 'Online Benutzer',
      online: 'online',
      allMessages: 'Alle Nachrichten',
      noMessages: 'Noch keine Nachrichten',
      startConversation: 'Starten Sie das Gespräch!',

      // Investment Allocation
      investmentAllocation: 'Investitionsallokation',
      myAllocation: 'Meine Allokation',
      stakeholderParticipation: 'Aktionärsbeteiligung',
      allocatedAmount: 'Zugewiesener Betrag',
      optedOut: 'Abgemeldet',
      setAllocation: 'Allokation festlegen',
      allocationSaved: 'Allokation gespeichert',
      saved: 'Gespeichert',
      allocated: 'zugewiesen',
      ofStakeholders: 'der Aktionäre',
      participationRate: 'Beteiligungsrate',
      optedOutDescription: 'Sie haben sich von der Investition in dieses Produkt abgemeldet. Sie können weiterhin an Bestellungen teilnehmen.',

      // Product Discussion
      productDiscussion: 'Produktdiskussion',
      discuss: 'Diskutieren',
      recentMessages: 'neue Nachrichten',
      joinDiscussion: 'Diskussion beitreten',
      noDiscussionsYet: 'Noch keine Diskussionen',
      startDiscussion: 'Starten Sie die Diskussion!',

      // Validation & Errors
      required: 'Erforderlich',
      invalid: 'Ungültig',
      invalidEmail: 'Ungültige E-Mail-Adresse',
      passwordTooShort: 'Passwort ist zu kurz',
      passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
      somethingWentWrong: 'Etwas ist schiefgelaufen',
      tryAgain: 'Erneut versuchen',
      noResults: 'Keine Ergebnisse gefunden',

      // Time
      today: 'Heute',
      yesterday: 'Gestern',
      thisWeek: 'Diese Woche',
      thisMonth: 'Dieser Monat',
      lastWeek: 'Letzte Woche',
      lastMonth: 'Letzter Monat',

      // Misc
      copyright: 'Alle Rechte vorbehalten',
      version: 'Version',
      help: 'Hilfe',
      support: 'Support',
      documentation: 'Dokumentation',
      privacyPolicy: 'Datenschutzrichtlinie',
      termsOfService: 'Nutzungsbedingungen'
    }
  },
  fr: {
    translation: {
      // Navigation
      dashboard: 'Tableau de bord',
      products: 'Produits',
      orders: 'Commandes',
      stakeholders: 'Actionnaires',
      marketing: 'Marketing',
      forecasting: 'Prévisions',
      shipping: 'Expédition',
      settings: 'Paramètres',
      stock: 'Stock',
      chat: 'Chat',

      // Common
      welcome: 'Bienvenue',
      welcomeBack: 'Bienvenue',
      search: 'Rechercher',
      searchPlaceholder: 'Rechercher...',
      filter: 'Filtrer',
      filterBy: 'Filtrer par',
      save: 'Enregistrer',
      saveChanges: 'Enregistrer les modifications',
      cancel: 'Annuler',
      delete: 'Supprimer',
      edit: 'Modifier',
      add: 'Ajouter',
      view: 'Voir',
      viewAll: 'Tout voir',
      loading: 'Chargement...',
      noData: 'Aucune donnée disponible',
      close: 'Fermer',
      confirm: 'Confirmer',
      back: 'Retour',
      next: 'Suivant',
      previous: 'Précédent',
      all: 'Tous',
      active: 'Actif',
      inactive: 'Inactif',
      status: 'Statut',
      actions: 'Actions',
      details: 'Détails',
      description: 'Description',
      date: 'Date',
      time: 'Heure',
      name: 'Nom',
      type: 'Type',
      amount: 'Montant',
      total: 'Total',
      price: 'Prix',
      quantity: 'Quantité',
      unit: 'Unité',
      notes: 'Notes',
      created: 'Créé',
      updated: 'Mis à jour',
      by: 'par',

      // Auth
      signIn: 'Connexion',
      signOut: 'Déconnexion',
      logout: 'Déconnexion',
      register: "S'inscrire",
      email: 'E-mail',
      password: 'Mot de passe',
      inviteCode: "Code d'invitation",
      forgotPassword: 'Mot de passe oublié?',
      rememberMe: 'Se souvenir de moi',

      // Dashboard
      heresWhatsHappening: "Voici ce qui se passe avec votre portefeuille",
      yourShares: 'Vos Actions',
      yourTier: 'Votre Niveau',
      totalPool: 'Pool Total',
      orderContribution: 'Contribution Commande',
      ownership: 'propriété',
      invested: 'investi',
      activeStakeholders: 'actionnaires actifs',
      participationShares: 'actions de participation',
      poolRevenue: 'Revenus du Pool',
      lastMonths: 'Derniers {count} mois',
      lastYear: "L'année dernière",
      shareDistributionByTier: 'Distribution des Actions par Niveau',
      activeGroupOrders: 'Commandes Groupées Actives',
      noActiveGroupOrders: 'Aucune commande groupée active',
      createOne: 'Créer une',
      participants: 'participants',
      complete: 'terminé',
      topStakeholders: 'Top Actionnaires',
      shares: 'actions',
      joinGroupOrder: 'Rejoindre une Commande Groupée',
      groupOrder: 'Commande Groupée',

      // Products
      productName: 'Nom du produit',
      category: 'Catégorie',
      categories: 'Catégories',
      basePrice: 'Prix de base',
      stockLevel: 'Niveau de stock',
      bulkPricing: 'Prix en gros',
      inStock: 'En stock',
      lowStock: 'Stock faible',
      outOfStock: 'Rupture de stock',
      addProduct: 'Ajouter un produit',
      editProduct: 'Modifier le produit',
      deleteProduct: 'Supprimer le produit',
      productDetails: 'Détails du produit',
      minQuantity: 'Quantité min.',
      discount: 'Remise',
      supplier: 'Fournisseur',
      sku: 'SKU',
      unitPrice: 'Prix unitaire',

      // Stock
      stockManagement: 'Gestion des Stocks',
      manageInventory: 'Gérez votre inventaire et niveaux de stock',
      currentStock: 'Stock Actuel',
      reserved: 'Réservé',
      available: 'Disponible',
      reorderPoint: 'Point de commande',
      leadTime: 'Délai',
      days: 'jours',
      location: 'Emplacement',
      warehouse: 'Entrepôt',
      lastUpdated: 'Dernière mise à jour',
      stockConfiguration: 'Configuration du Stock',
      updateStock: 'Mettre à jour le stock',
      stockHistory: 'Historique du stock',
      lowStockAlert: 'Alerte stock faible',
      outOfStockAlert: 'Alerte rupture de stock',
      reorderRequired: 'Réapprovisionnement requis',
      stockStatus: 'État du stock',
      high: 'Élevé',
      medium: 'Moyen',
      low: 'Faible',
      critical: 'Critique',
      units: 'unités',

      // Orders
      groupOrders: 'Commandes groupées',
      myOrders: 'Mes commandes',
      joinOrder: 'Rejoindre',
      createOrder: 'Créer commande',
      orderStatus: 'Statut commande',
      pending: 'En attente',
      confirmed: 'Confirmé',
      processing: 'En cours',
      shipped: 'Expédié',
      delivered: 'Livré',
      cancelled: 'Annulé',
      orderDate: 'Date de commande',
      deliveryDate: 'Date de livraison',
      trackingNumber: 'Numéro de suivi',
      orderTotal: 'Total commande',
      orderDetails: 'Détails commande',
      orderHistory: 'Historique commandes',
      targetQuantity: 'Quantité cible',
      currentQuantity: 'Quantité actuelle',
      progressToTarget: 'Progression vers objectif',
      joinThisOrder: 'Rejoindre cette commande',
      leaveOrder: 'Quitter la commande',
      closeOrder: 'Fermer la commande',

      // Stakeholders
      totalShares: 'Total actions',
      investment: 'Investissement',
      tier: 'Niveau',
      addInvestment: 'Ajouter investissement',
      invite: 'Inviter',
      inviteStakeholder: 'Inviter un actionnaire',
      stakeholderDetails: "Détails de l'actionnaire",
      memberSince: 'Membre depuis',
      lastActivity: 'Dernière activité',
      totalInvestment: 'Investissement total',
      sharePercentage: "Pourcentage d'actions",
      platinum: 'Platine',
      gold: 'Or',
      silver: 'Argent',
      bronze: 'Bronze',
      investmentHistory: "Historique d'investissement",
      dividendHistory: 'Historique des dividendes',

      // Marketing
      campaigns: 'Campagnes',
      activeCampaigns: 'Campagnes Actives',
      createCampaign: 'Créer une campagne',
      campaignName: 'Nom de la campagne',
      campaignType: 'Type de campagne',
      startDate: 'Date de début',
      endDate: 'Date de fin',
      budget: 'Budget',
      spent: 'Dépensé',
      remaining: 'Restant',
      impressions: 'Impressions',
      clicks: 'Clics',
      conversions: 'Conversions',
      roi: 'ROI',
      performance: 'Performance',
      analytics: 'Analytique',
      reach: 'Portée',
      engagement: 'Engagement',

      // Forecasting
      priceForecast: 'Prévision des prix',
      marketTrends: 'Tendances du marché',
      demandPrediction: 'Prévision de la demande',
      forecastPeriod: 'Période de prévision',
      confidence: 'Confiance',
      predicted: 'Prévu',
      actual: 'Réel',
      variance: 'Variance',
      trend: 'Tendance',
      upward: 'Haussière',
      downward: 'Baissière',
      stable: 'Stable',
      volatile: 'Volatile',

      // Shipping
      shipments: 'Expéditions',
      trackShipment: "Suivre l'expédition",
      shippingAddress: "Adresse d'expédition",
      billingAddress: 'Adresse de facturation',
      carrier: 'Transporteur',
      estimatedDelivery: 'Livraison estimée',
      actualDelivery: 'Livraison réelle',
      shippingCost: "Frais d'expédition",
      shippingMethod: "Méthode d'expédition",
      standard: 'Standard',
      express: 'Express',
      overnight: 'Nuit',
      aggregatedShipping: 'Expédition groupée',
      individualShipping: 'Expédition individuelle',
      inTransit: 'En transit',
      outForDelivery: 'En cours de livraison',
      deliveryException: 'Exception de livraison',

      // Settings
      profile: 'Profil',
      profileInformation: 'Informations du profil',
      notifications: 'Notifications',
      notificationPreferences: 'Préférences de notification',
      language: 'Langue',
      theme: 'Thème',
      darkMode: 'Mode sombre',
      lightMode: 'Mode clair',
      dark: 'Sombre',
      light: 'Clair',
      display: 'Affichage',
      displaySettings: "Paramètres d'affichage",
      currency: 'Devise',
      timezone: 'Fuseau horaire',
      emailNotifications: 'Notifications par e-mail',
      pushNotifications: 'Notifications push',
      orderUpdates: 'Mises à jour des commandes',
      priceAlerts: 'Alertes de prix',
      marketingEmails: 'E-mails marketing',
      receiveNotifications: 'Recevoir des notifications par e-mail',
      browserNotifications: 'Notifications push du navigateur',
      updatesOnOrders: 'Mises à jour sur vos commandes et expéditions',
      alertsWhenPrices: 'Alertes lors de changements de prix importants',
      newsPromotions: 'Actualités, promotions et mises à jour',
      security: 'Sécurité',
      securitySettings: 'Paramètres de sécurité',
      changePassword: 'Changer le mot de passe',
      updatePassword: 'Mettre à jour votre mot de passe',
      twoFactorAuth: 'Authentification à deux facteurs',
      addExtraSecurity: 'Ajouter une couche de sécurité supplémentaire',
      activeSessions: 'Sessions actives',
      manageDevices: 'Gérer vos appareils connectés',
      deleteAccount: 'Supprimer le compte',
      permanentlyDelete: 'Supprimer définitivement votre compte et vos données',
      integrations: 'Intégrations',
      connectedServices: 'Services connectés',
      connected: 'Connecté',
      connect: 'Connecter',
      disconnect: 'Déconnecter',
      fullName: 'Nom complet',
      streetAddress: 'Adresse',
      city: 'Ville',
      postalCode: 'Code postal',
      country: 'Pays',
      defaultShippingAddress: "Adresse d'expédition par défaut",
      preferAggregatedShipping: "Préférer l'expédition groupée",
      combineOrders: "Combiner les commandes avec d'autres actionnaires pour réduire les frais d'expédition",
      settingsSaved: 'Paramètres enregistrés avec succès',
      failedToSave: "Échec de l'enregistrement",
      saving: 'Enregistrement...',
      brightTheme: 'Thème clair',
      easyOnEyes: 'Confortable pour les yeux',
      enable: 'Activer',
      change: 'Modifier',

      // Chat
      typeMessage: 'Tapez un message...',
      send: 'Envoyer',
      onlineUsers: 'Utilisateurs en ligne',
      online: 'en ligne',
      allMessages: 'Tous les messages',
      noMessages: 'Pas encore de messages',
      startConversation: 'Commencez la conversation!',

      // Investment Allocation
      investmentAllocation: "Allocation d'investissement",
      myAllocation: 'Mon Allocation',
      stakeholderParticipation: 'Participation des actionnaires',
      allocatedAmount: 'Montant alloué',
      optedOut: 'Désactivé',
      setAllocation: "Définir l'allocation",
      allocationSaved: 'Allocation enregistrée',
      saved: 'Enregistré',
      allocated: 'alloué',
      ofStakeholders: 'des actionnaires',
      participationRate: 'Taux de participation',
      optedOutDescription: "Vous vous êtes désabonné de l'investissement pour ce produit. Vous pouvez toujours participer aux commandes.",

      // Product Discussion
      productDiscussion: 'Discussion du produit',
      discuss: 'Discuter',
      recentMessages: 'messages récents',
      joinDiscussion: 'Rejoindre la discussion',
      noDiscussionsYet: 'Pas encore de discussions',
      startDiscussion: 'Commencez la discussion!',

      // Validation & Errors
      required: 'Requis',
      invalid: 'Invalide',
      invalidEmail: 'Adresse e-mail invalide',
      passwordTooShort: 'Mot de passe trop court',
      passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
      somethingWentWrong: "Quelque chose s'est mal passé",
      tryAgain: 'Réessayer',
      noResults: 'Aucun résultat trouvé',

      // Time
      today: "Aujourd'hui",
      yesterday: 'Hier',
      thisWeek: 'Cette semaine',
      thisMonth: 'Ce mois',
      lastWeek: 'Semaine dernière',
      lastMonth: 'Mois dernier',

      // Misc
      copyright: 'Tous droits réservés',
      version: 'Version',
      help: 'Aide',
      support: 'Support',
      documentation: 'Documentation',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: "Conditions d'utilisation"
    }
  },
  es: {
    translation: {
      // Navigation
      dashboard: 'Panel',
      products: 'Productos',
      orders: 'Pedidos',
      stakeholders: 'Accionistas',
      marketing: 'Marketing',
      forecasting: 'Pronóstico',
      shipping: 'Envío',
      settings: 'Configuración',
      stock: 'Inventario',
      chat: 'Chat',

      // Common
      welcome: 'Bienvenido',
      welcomeBack: 'Bienvenido de nuevo',
      search: 'Buscar',
      searchPlaceholder: 'Buscar...',
      filter: 'Filtrar',
      filterBy: 'Filtrar por',
      save: 'Guardar',
      saveChanges: 'Guardar cambios',
      cancel: 'Cancelar',
      delete: 'Eliminar',
      edit: 'Editar',
      add: 'Agregar',
      view: 'Ver',
      viewAll: 'Ver todo',
      loading: 'Cargando...',
      noData: 'No hay datos disponibles',
      close: 'Cerrar',
      confirm: 'Confirmar',
      back: 'Atrás',
      next: 'Siguiente',
      previous: 'Anterior',
      all: 'Todos',
      active: 'Activo',
      inactive: 'Inactivo',
      status: 'Estado',
      actions: 'Acciones',
      details: 'Detalles',
      description: 'Descripción',
      date: 'Fecha',
      time: 'Hora',
      name: 'Nombre',
      type: 'Tipo',
      amount: 'Cantidad',
      total: 'Total',
      price: 'Precio',
      quantity: 'Cantidad',
      unit: 'Unidad',
      notes: 'Notas',
      created: 'Creado',
      updated: 'Actualizado',
      by: 'por',

      // Auth
      signIn: 'Iniciar sesión',
      signOut: 'Cerrar sesión',
      logout: 'Cerrar sesión',
      register: 'Registrarse',
      email: 'Correo electrónico',
      password: 'Contraseña',
      inviteCode: 'Código de invitación',
      forgotPassword: '¿Olvidaste tu contraseña?',
      rememberMe: 'Recuérdame',

      // Dashboard
      heresWhatsHappening: "Esto es lo que está pasando con tu cartera",
      yourShares: 'Tus Acciones',
      yourTier: 'Tu Nivel',
      totalPool: 'Pool Total',
      orderContribution: 'Contribución de Pedido',
      ownership: 'propiedad',
      invested: 'invertido',
      activeStakeholders: 'accionistas activos',
      participationShares: 'acciones de participación',
      poolRevenue: 'Ingresos del Pool',
      lastMonths: 'Últimos {count} meses',
      lastYear: 'Último año',
      shareDistributionByTier: 'Distribución de Acciones por Nivel',
      activeGroupOrders: 'Pedidos Grupales Activos',
      noActiveGroupOrders: 'No hay pedidos grupales activos',
      createOne: 'Crear uno',
      participants: 'participantes',
      complete: 'completado',
      topStakeholders: 'Top Accionistas',
      shares: 'acciones',
      joinGroupOrder: 'Unirse a Pedido Grupal',
      groupOrder: 'Pedido Grupal',

      // Products
      productName: 'Nombre del producto',
      category: 'Categoría',
      categories: 'Categorías',
      basePrice: 'Precio base',
      stockLevel: 'Nivel de inventario',
      bulkPricing: 'Precio por volumen',
      inStock: 'En stock',
      lowStock: 'Stock bajo',
      outOfStock: 'Agotado',
      addProduct: 'Agregar producto',
      editProduct: 'Editar producto',
      deleteProduct: 'Eliminar producto',
      productDetails: 'Detalles del producto',
      minQuantity: 'Cantidad mín.',
      discount: 'Descuento',
      supplier: 'Proveedor',
      sku: 'SKU',
      unitPrice: 'Precio unitario',

      // Stock
      stockManagement: 'Gestión de Inventario',
      manageInventory: 'Gestiona tu inventario y niveles de stock',
      currentStock: 'Stock Actual',
      reserved: 'Reservado',
      available: 'Disponible',
      reorderPoint: 'Punto de reorden',
      leadTime: 'Tiempo de entrega',
      days: 'días',
      location: 'Ubicación',
      warehouse: 'Almacén',
      lastUpdated: 'Última actualización',
      stockConfiguration: 'Configuración de Stock',
      updateStock: 'Actualizar stock',
      stockHistory: 'Historial de stock',
      lowStockAlert: 'Alerta de stock bajo',
      outOfStockAlert: 'Alerta de agotado',
      reorderRequired: 'Reorden requerido',
      stockStatus: 'Estado del stock',
      high: 'Alto',
      medium: 'Medio',
      low: 'Bajo',
      critical: 'Crítico',
      units: 'unidades',

      // Orders
      groupOrders: 'Pedidos grupales',
      myOrders: 'Mis pedidos',
      joinOrder: 'Unirse',
      createOrder: 'Crear pedido',
      orderStatus: 'Estado del pedido',
      pending: 'Pendiente',
      confirmed: 'Confirmado',
      processing: 'Procesando',
      shipped: 'Enviado',
      delivered: 'Entregado',
      cancelled: 'Cancelado',
      orderDate: 'Fecha de pedido',
      deliveryDate: 'Fecha de entrega',
      trackingNumber: 'Número de seguimiento',
      orderTotal: 'Total del pedido',
      orderDetails: 'Detalles del pedido',
      orderHistory: 'Historial de pedidos',
      targetQuantity: 'Cantidad objetivo',
      currentQuantity: 'Cantidad actual',
      progressToTarget: 'Progreso hacia objetivo',
      joinThisOrder: 'Unirse a este pedido',
      leaveOrder: 'Abandonar pedido',
      closeOrder: 'Cerrar pedido',

      // Stakeholders
      totalShares: 'Acciones totales',
      investment: 'Inversión',
      tier: 'Nivel',
      addInvestment: 'Agregar inversión',
      invite: 'Invitar',
      inviteStakeholder: 'Invitar accionista',
      stakeholderDetails: 'Detalles del accionista',
      memberSince: 'Miembro desde',
      lastActivity: 'Última actividad',
      totalInvestment: 'Inversión total',
      sharePercentage: 'Porcentaje de acciones',
      platinum: 'Platino',
      gold: 'Oro',
      silver: 'Plata',
      bronze: 'Bronce',
      investmentHistory: 'Historial de inversión',
      dividendHistory: 'Historial de dividendos',

      // Marketing
      campaigns: 'Campañas',
      activeCampaigns: 'Campañas Activas',
      createCampaign: 'Crear campaña',
      campaignName: 'Nombre de la campaña',
      campaignType: 'Tipo de campaña',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de fin',
      budget: 'Presupuesto',
      spent: 'Gastado',
      remaining: 'Restante',
      impressions: 'Impresiones',
      clicks: 'Clics',
      conversions: 'Conversiones',
      roi: 'ROI',
      performance: 'Rendimiento',
      analytics: 'Analíticas',
      reach: 'Alcance',
      engagement: 'Interacción',

      // Forecasting
      priceForecast: 'Pronóstico de precios',
      marketTrends: 'Tendencias del mercado',
      demandPrediction: 'Predicción de demanda',
      forecastPeriod: 'Período de pronóstico',
      confidence: 'Confianza',
      predicted: 'Predicho',
      actual: 'Real',
      variance: 'Varianza',
      trend: 'Tendencia',
      upward: 'Alcista',
      downward: 'Bajista',
      stable: 'Estable',
      volatile: 'Volátil',

      // Shipping
      shipments: 'Envíos',
      trackShipment: 'Rastrear envío',
      shippingAddress: 'Dirección de envío',
      billingAddress: 'Dirección de facturación',
      carrier: 'Transportista',
      estimatedDelivery: 'Entrega estimada',
      actualDelivery: 'Entrega real',
      shippingCost: 'Costo de envío',
      shippingMethod: 'Método de envío',
      standard: 'Estándar',
      express: 'Express',
      overnight: 'Nocturno',
      aggregatedShipping: 'Envío agrupado',
      individualShipping: 'Envío individual',
      inTransit: 'En tránsito',
      outForDelivery: 'En reparto',
      deliveryException: 'Excepción de entrega',

      // Settings
      profile: 'Perfil',
      profileInformation: 'Información del perfil',
      notifications: 'Notificaciones',
      notificationPreferences: 'Preferencias de notificación',
      language: 'Idioma',
      theme: 'Tema',
      darkMode: 'Modo oscuro',
      lightMode: 'Modo claro',
      dark: 'Oscuro',
      light: 'Claro',
      display: 'Pantalla',
      displaySettings: 'Configuración de pantalla',
      currency: 'Moneda',
      timezone: 'Zona horaria',
      emailNotifications: 'Notificaciones por correo',
      pushNotifications: 'Notificaciones push',
      orderUpdates: 'Actualizaciones de pedidos',
      priceAlerts: 'Alertas de precios',
      marketingEmails: 'Correos de marketing',
      receiveNotifications: 'Recibir notificaciones por correo',
      browserNotifications: 'Notificaciones push del navegador',
      updatesOnOrders: 'Actualizaciones sobre tus pedidos y envíos',
      alertsWhenPrices: 'Alertas cuando los precios cambian significativamente',
      newsPromotions: 'Noticias, promociones y actualizaciones',
      security: 'Seguridad',
      securitySettings: 'Configuración de seguridad',
      changePassword: 'Cambiar contraseña',
      updatePassword: 'Actualiza la contraseña de tu cuenta',
      twoFactorAuth: 'Autenticación de dos factores',
      addExtraSecurity: 'Añade una capa extra de seguridad',
      activeSessions: 'Sesiones activas',
      manageDevices: 'Gestiona tus dispositivos conectados',
      deleteAccount: 'Eliminar cuenta',
      permanentlyDelete: 'Elimina permanentemente tu cuenta y datos',
      integrations: 'Integraciones',
      connectedServices: 'Servicios conectados',
      connected: 'Conectado',
      connect: 'Conectar',
      disconnect: 'Desconectar',
      fullName: 'Nombre completo',
      streetAddress: 'Dirección',
      city: 'Ciudad',
      postalCode: 'Código postal',
      country: 'País',
      defaultShippingAddress: 'Dirección de envío predeterminada',
      preferAggregatedShipping: 'Preferir envío agrupado',
      combineOrders: 'Combinar pedidos con otros accionistas para reducir costos de envío',
      settingsSaved: 'Configuración guardada exitosamente',
      failedToSave: 'Error al guardar',
      saving: 'Guardando...',
      brightTheme: 'Tema claro',
      easyOnEyes: 'Cómodo para los ojos',
      enable: 'Activar',
      change: 'Cambiar',

      // Chat
      typeMessage: 'Escribe un mensaje...',
      send: 'Enviar',
      onlineUsers: 'Usuarios en línea',
      online: 'en línea',
      allMessages: 'Todos los mensajes',
      noMessages: 'Aún no hay mensajes',
      startConversation: '¡Inicia la conversación!',

      // Investment Allocation
      investmentAllocation: 'Asignación de inversión',
      myAllocation: 'Mi Asignación',
      stakeholderParticipation: 'Participación de accionistas',
      allocatedAmount: 'Monto asignado',
      optedOut: 'Excluido',
      setAllocation: 'Establecer asignación',
      allocationSaved: 'Asignación guardada',
      saved: 'Guardado',
      allocated: 'asignado',
      ofStakeholders: 'de accionistas',
      participationRate: 'Tasa de participación',
      optedOutDescription: 'Te has excluido de la inversión en este producto. Aún puedes participar en pedidos.',

      // Product Discussion
      productDiscussion: 'Discusión del producto',
      discuss: 'Discutir',
      recentMessages: 'mensajes recientes',
      joinDiscussion: 'Unirse a la discusión',
      noDiscussionsYet: 'Aún no hay discusiones',
      startDiscussion: '¡Inicia la discusión!',

      // Validation & Errors
      required: 'Requerido',
      invalid: 'Inválido',
      invalidEmail: 'Correo electrónico inválido',
      passwordTooShort: 'La contraseña es muy corta',
      passwordsDoNotMatch: 'Las contraseñas no coinciden',
      somethingWentWrong: 'Algo salió mal',
      tryAgain: 'Intentar de nuevo',
      noResults: 'No se encontraron resultados',

      // Time
      today: 'Hoy',
      yesterday: 'Ayer',
      thisWeek: 'Esta semana',
      thisMonth: 'Este mes',
      lastWeek: 'Semana pasada',
      lastMonth: 'Mes pasado',

      // Misc
      copyright: 'Todos los derechos reservados',
      version: 'Versión',
      help: 'Ayuda',
      support: 'Soporte',
      documentation: 'Documentación',
      privacyPolicy: 'Política de privacidad',
      termsOfService: 'Términos de servicio'
    }
  }
}

// Initialize i18next
i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: localStorage.getItem('conceptshop-language') || 'en',
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    }
  })

const LanguageContext = createContext(null)

const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'es', name: 'Español', flag: '🇪🇸' }
]

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('conceptshop-language') || 'en'
  })

  const changeLanguage = (lang) => {
    setLanguageState(lang)
    localStorage.setItem('conceptshop-language', lang)
    i18n.changeLanguage(lang)
    // Update HTML lang attribute for accessibility
    document.documentElement.lang = lang
  }

  // Set initial HTML lang attribute
  useEffect(() => {
    document.documentElement.lang = language
  }, [])

  return (
    <LanguageContext.Provider value={{
      language,
      changeLanguage,
      setLanguage: changeLanguage, // alias for backwards compatibility
      languages: LANGUAGES,
      t: i18n.t.bind(i18n)
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

export { i18n }
